# Generated by Django 2.1.7 on 2019-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('user_id', models.IntegerField(db_column='User_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_name', max_length=150)),
                ('module_name', models.CharField(db_column='Module_name', max_length=100)),
                ('time_login', models.DateTimeField(db_column='Time_login')),
                ('logout_time', models.DateTimeField(blank=True, db_column='LogOut_time', null=True)),
                ('is_success', models.IntegerField(db_column='Is_success')),
                ('trk_ip_address', models.CharField(db_column='Trk_Ip_address', max_length=50)),
                ('action_date', models.DateTimeField(db_column='Action_date')),
            ],
            options={
                'db_table': 'log_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc_id', models.IntegerField()),
                ('soc_name', models.CharField(max_length=150)),
                ('soc_addr', models.CharField(max_length=300)),
                ('work_area', models.CharField(max_length=150)),
                ('dist_id', models.IntegerField()),
                ('dist_name', models.CharField(max_length=200)),
                ('division_name', models.CharField(blank=True, max_length=150, null=True)),
                ('stype_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField()),
                ('ren_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'soc_table',
                'managed': False,
            },
        ),
    ]
