# Generated by Django 2.1.7 on 2019-04-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soctable',
            table='soc_master',
        ),
    ]
