# Generated by Django 2.1.7 on 2019-04-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190423_1324'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soctable',
            table='soc_table',
        ),
    ]
