# Generated by Django 2.1.7 on 2019-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190424_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
