# Generated by Django 2.1.7 on 2019-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc_id', models.IntegerField()),
                ('soc_name', models.CharField(max_length=200)),
                ('soc_addr', models.CharField(max_length=200)),
                ('work_area', models.CharField(max_length=150)),
                ('dist_id', models.IntegerField()),
                ('dist_name', models.CharField(max_length=150)),
                ('division_name', models.CharField(max_length=200)),
                ('stype_name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(max_length=150)),
                ('reg_date', models.DateField()),
                ('ren_date', models.DateField()),
                ('app_date', models.DateField()),
            ],
            options={
                'db_table': 'soc_master',
                'managed': False,
            },
        ),
    ]
